import { injectable, inject } from "inversify";
import { Database, loadSql, mapRowToBean, mapRowsToBeans } from "@seasar2ts/core";
import { User } from "../entity/User";

// Generated by Seasar2ts for S2Dao: UserDao
@injectable()
export class UserDao {
  constructor(
    @inject("Database") private db: Database
  ) {}

  async find(id: number): Promise<User> {
    const sql = loadSql("user/find.sql");
    const row = await this.db.queryOne(sql, id);
    return mapRowToBean(row, User as any);
  }

  async findAll(): Promise<User[]> {
    const sql = loadSql("user/findAll.sql");
    const rows = await this.db.queryList(sql, undefined);
    return mapRowsToBeans(rows, User as any);
  }

  async update(user: User): Promise<number> {
    const sql = loadSql("user/update.sql");
    const count = await this.db.execute(sql, user);
    return count;
  }

}