import { injectable, inject } from "inversify";
import { UserDao } from "../dao/UserDao";
import { User } from "../entity/User";

// Generated by Seasar2ts for: UserService
@injectable()
export class UserService {
  constructor(
    @inject("UserDao") private userDao: UserDao
  ) {}

  async getUser(id: number): Promise<User> {
    // TODO: implement business logic ported from Java
    return null as any;
  }

}