import { injectable, inject } from "inversify";
import { UserService } from "../logic/UserService";
import { User } from "../entity/User";

// Generated by Seasar2ts for: UserAction
@injectable()
export class UserAction {
  constructor(
    @inject("UserService") private userService: UserService
  ) {}

  index(): string {
    // TODO: implement business logic ported from Java
    return "";
  }

  show(id: number): User {
    // TODO: implement business logic ported from Java
    return null as any;
  }

}